on: [pull_request]

name: wasm-pack

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test on Chrome
        run: wasm-pack test --headless --chrome --all-features

      - name: Test on Firefox
        run: wasm-pack test --headless --firefox --all-features

  build-size:
    name: Build size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Assert bundle size (gzipped)
        run: make test-wasm-size
